apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: sentinelai

rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - services
      - endpoints
      - namespaces
    verbs:
      - get
      - list
      - watch