apiVersion: v1
kind: ServiceAccount

metadata:
  name: promtail
  namespace: logging
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: sentinelai

  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: sentinelai