apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: loki-pvc
  namespace: logging

  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: sentinelai

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi