import os

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST")
RABBITMQ_PORT = int(os.getenv("RABBITMQ_PORT"))

RABBITMQ_USERNAME = os.getenv("RABBITMQ_USERNAME")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD")

EXCHANGE_NAME = os.getenv("EXCHANGE_NAME")

INCIDENT_ROUTING_KEY = os.getenv("INCIDENT_ROUTING_KEY")

INCIDENT_QUEUE = os.getenv("INCIDENT_QUEUE")
