apiVersion: apps/v1
kind: Deployment

metadata:
  name: sentinel-worker
  namespace: sentinel

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sentinel-worker

  template:
    metadata:
      labels:
        app: sentinel-worker

    spec:
      containers:
        - name: sentinel-worker

          image: sentinel-worker:latest
          imagePullPolicy: Never

          envFrom:
            - secretRef:
                name: sentinel-env